Script started on Sat Aug  1 00:09:09 2020

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
[?1034hbash-3.2$ ./prje[K[Koject[K[K[K[K[K[K[Kproject5_Fan_wzf0009.cpp[K[K[K[K [K
Banner id: 904035575
producer produce item 7
consumer consume item 7
producer produce item 14
consumer consume item 14
producer produce item 21
consumer consume item 21
producer produce item 28
consumer consume item 28
producer produce item 35
consumer consume item 35
producer produce item 42
consumer consume item 42
producer produce item 49
consumer consume item 49
producer produce item 56
consumer consume item 56
producer produce item 63
consumer consume item 63
producer produce item 70
consumer consume item 70
bash-3.2$ exit
exit

Script done on Sat Aug  1 00:10:01 2020
